title: <p align="center"> Marcell Llerena </p>

description:
  <p align="justify">
    I am pursing MS degree in Computer Science at San Pablo Catholic University.
    <br><br>
    My current research focus in few shot learning and meta-learning for deep neural networks.
    <br><br>
  </p>

theme: jekyll-theme-minimal

github:
  is\_project\_page:false